### ISSUE TITLE
"nav-item" CSS class is overrided by Bulma

### ISSUE THREAD

**Issue by bestblazor** [Blazor-School/Blazor-Library-Public-Issue-Tracker#1]
Hi,
I am trying to create a navigation bar with the CSS "nav-item". I am using Blazor Library with Bulma and the Bulma CSS override the Blazor Library CSS. I want to use the color scheme of Blazor Library instead of Bulma.

**Comment by hevilhuy** [comment]
Hi,
When generate the CSS classes, we don't use `!important` so that developers can freely customize the library. If you want to use our color scheme instead of Bulma, you can use the default color in the library. Look for the variables begin with "blazor-" as follow:
![image](https://github.com/Blazor-School/Blazor-Library-Public-Issue-Tracker/assets/17383256/4b8eb02f-dfe9-4de3-a6e1-7554ebd4be74)

Happy coding!
